partial nullsafety support (in the generated code)
timfreiheit/r_flutter pull request #27
Opened 2021-03-20 17:55 UTC by vishna

`r_flutter` generates now null safe code. If you update to v 7.0.0, your project should use dart 2.12. Let's drive the ecosystem to null safety 🚀

Code generator itself is not null safe yet (I'll see if I can update it all as my next step)

- update example to dart 2.12
- update platform clients
- add macos/web clients
- generate i18n class correctly for nullsafe
- make tests pass
- update codegen's deps to nullsafe (most of them I believe)

issue #24

2021-03-20 18:40 UTC, timfreiheit commented
awesome. thank you very much. 
I will prepare a release for this tomorrow

2021-03-21 10:34 UTC, timfreiheit requested changes

2021-03-21 10:34 UTC, timfreiheit commented on CHANGELOG.md
> +  * r_flutter generates now nullsafe code, if you update to v 7.0.0, your project should use dart 2.12
this should be 0.7.0

2021-03-21 10:34 UTC, timfreiheit commented on lib/src/model/resources.dart
> +// class StringReference {
seams like this class can be removed

2021-03-21 11:02 UTC, vishna commented on CHANGELOG.md
> +  * r_flutter generates now nullsafe code, if you update to v 7.0.0, your project should use dart 2.12
fixed

2021-03-21 11:02 UTC, vishna commented on lib/src/model/resources.dart
> +// class StringReference {
fixed

2021-03-21 11:04 UTC, vishna commented
@timfreiheit pushed the amends

2021-03-21 11:06 UTC, merged